version: "3.9"

x-template-backend:
  &template_backend
  user: web
  build:
    context: .
  env_file:
    - .env

services:
  backend:
    << : *template_backend
    container_name: backend_container
    command: python3 start.py
    ports:
      - "5000:5000"

  faust:
    <<: *template_backend
    container_name: faust
    command: faust -A src.agents worker --without-web -l info
    restart: on-failure

  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper
    env_file:
      - .env

  kafka:
    image: bitnami/kafka:3.0.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    volumes:
      - kafka-data:/data/kafka/
    env_file:
      - .env

  clickhouse:
    image: clickhouse/clickhouse-server:21.8.11.4
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./compose-services-data/clickhouse/node1:/etc/clickhouse-server
      - clickhouse-data:/data/clickhouse/
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:z
    depends_on:
      - zookeeper

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    environment:
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./logs/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /tmp/logs/nginx/:/var/log/nginx/
    logging:
      options:
        tag: nginx
    depends_on:
      - backend
    ports:
      - 8080:80

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.2
    container_name: filebeat
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./logs/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: filebeat -e -strict.perms=false
    depends_on:
      - backend
      - nginx
      - logstash
      - elasticsearch
      - kibana
    links:
      - logstash

volumes:
  kafka-data:
  clickhouse-data:

networks:
  default:
    name: ugc-network